package com.example.hellokitty.navigation

const val ROUT_HOME = "home"
const val ROUT_ABOUT = "about"
const val ROUT_LOGIN = "login"
const val ROUT_REGISTER = "register"
const val ROUT_SPLASH = "splash"
const val ROUT_START = "start"
const val ROUT_PERSIAN = "persian"
const val ROUT_RAGDOLL = "ragdoll"
const val ROUT_RAGAMUFFIN = "ragamuffin"
const val ROUT_WIREHAIR = "wirehair"
const val ROUT_MAINECOON = "mainecoon"
const val ROUT_CARD = "card"
const val ROUT_MPESA = "mpesa"
const val ROUT_PAYMENT = "payment"
